sudo: required
services:
  - docker

scripts:
  - docker build -t jasoncollins/node .
  - docker images jasoncollins/node

before_deploy:
  - docker login -u <username> -p <password>

deploy:
  provider: script
  script: docker push jasoncollins/node
  on:
    branch: main

